## Mammifères marins

```{r}
RenderData(type = 'Mammifères marins')
```

### Statut de la caractérisation

Travail avec le ROMM pour obtenir une caractérisation de la distribution des mammifères marins dans la zone d'étude.

Plan pour cette couche de données :

- Plan A : Données issues du guide qui sera publié le 31 mars 2021
  - Communications avec ROMM pour partage des données
- Plan B : Données opportunistes du ROMM pour créer cartes de distributions des mammifères marins

#### Mise à jour 2020-12-15 :

Nous aurons accès aux données du Mariner's guide en février. Ce guide sera publié en mars, mais nous aurons accès aux données en février de notre côté.


## Autres notes

Liste des espèces pour lesquelles nous auront des informations:

1. Beluga
2. North Atlantic right whale
3. Northern Bottlenose whale
4. Blue whale
5. Fin whale
6. Sei whale
7. Minke whale
8. Humpback whale
9. Sperm whale

Pour plus de
WhaleSightings.XMAR@dfo-mpo.gc.ca

Si on souhaite obtenir plus de données rapidement sur d’autres espèces, faire une nouvelle demande des données XMAR auprès de Pam Emery au MPO (WhaleSightings.XMAR@dfo-mpo.gc.ca).
